name: Auto Tag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: paulhatch/semantic-version@v5.3.0
      with:
        tag_prefix: "v"
        major_pattern: "^update:"
        major_regexp_flags: "i"  # 'i' flag for case-insensitive matching, remove if case sensitivity is needed
        minor_pattern: "(MINOR)"
        minor_regexp_flags: ""
        version_format: "${major}.${minor}.${patch}"

    - name: Create git tag
      if: steps.semver.outputs.new_version != ''
      run: |
        git tag ${{ steps.semver.outputs.version }}
        
    - name: Push git tag
      run: git push origin ${{ steps.semver.outputs.version }}
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.semver.outputs.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest     
        platforms: linux/amd64,linux/arm64,linux/arm/v8
