name: Auto Tag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: paulhatch/semantic-version@v5.3.0
      with:
        tag_prefix: "v"
        major_pattern: "^update:"
        major_regexp_flags: "i"  # 'i' flag for case-insensitive matching, remove if case sensitivity is needed
        minor_pattern: "(MINOR)"
        minor_regexp_flags: ""
        version_format: "${major}.${minor}.${patch}"

    - name: Create tag
      if: steps.semver.outputs.new_version != ''
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${{ steps.semver.outputs.version }}`,
            sha: context.sha
          })
